# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/qqc2-desktop-style': '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'frameworks/kconfigwidgets' : '@latest'
    'frameworks/kwindowsystem' : '@latest'
    'frameworks/kxmlgui' : '@latest'
    'frameworks/kcontacts' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-calendar' : '@same'
    'pim/calendarsupport' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kmime' : '@same'
    'pim/eventviews' : '@same'
    'pim/kdepim-runtime' : '@same'
    'pim/mailcommon' : '@same'
    'pim/pimcommon' : '@same'
    'frameworks/kirigami' : '@latest'

Options:
  # The add_akonadi_isolated_test_advanced functions used in our tests CMake
  # does not distinguish between -DAKONADI_RUN_{backend}_ISOLATED_TESTS
  # arguments being set to true or false -- it only checks if they are
  # defined
  cmake-options: "-DAKONADI_RUN_SQLITE_ISOLATED_TESTS=TRUE"
  require-passing-tests-on: ['Linux']
